"""Deterministic read-only analytics over ClickHouse marts."""

from wb_insight.analytics.models import (
    AmbiguousMetricError,
    AnalyticalError,
    CorrelationMethod,
    CorrelationPair,
    CorrelationResult,
    CountryCatalogEntry,
    CountryComparisonEntry,
    CountryComparisonResult,
    CountrySnapshotResult,
    CurrentRunSummary,
    DataQualityEntry,
    DataQualityResult,
    DimensionRequiredError,
    IndicatorCatalogEntry,
    MetricNotFoundError,
    MetricRequest,
    RepositoryReadiness,
    ResolvedMetric,
    ResultLimitError,
    SeriesCoverage,
    SnapshotMode,
    SnapshotPoint,
    TimeseriesPoint,
    TimeseriesResult,
    TrendResult,
)
from wb_insight.analytics.repository import AnalyticalRepository
from wb_insight.analytics.statistics import (
    calculate_correlation,
    calculate_trend,
    compare_countries,
)

__all__ = [
    "AmbiguousMetricError",
    "AnalyticalError",
    "AnalyticalRepository",
    "CorrelationMethod",
    "CorrelationPair",
    "CorrelationResult",
    "CountryCatalogEntry",
    "CountryComparisonEntry",
    "CountryComparisonResult",
    "CountrySnapshotResult",
    "CurrentRunSummary",
    "DataQualityEntry",
    "DataQualityResult",
    "DimensionRequiredError",
    "IndicatorCatalogEntry",
    "MetricNotFoundError",
    "MetricRequest",
    "RepositoryReadiness",
    "ResolvedMetric",
    "ResultLimitError",
    "SeriesCoverage",
    "SnapshotMode",
    "SnapshotPoint",
    "TimeseriesPoint",
    "TimeseriesResult",
    "TrendResult",
    "calculate_correlation",
    "calculate_trend",
    "compare_countries",
]
